openapi: 3.0.0
info:
  version: 1.0.0
  title: Wedding API
  description: API documentation for managing wedding invitation
servers:
  - url: http://localhost:9002 # Dev server URL
    description: API Dev
  - url: http://156.67.220.149:9002 # Prod server URL
    description: Api Prod

paths:
  /wishes:
    get:
      tags:
        - Wishes   
      summary: Get Wishes
      description: Retrieve a list of wishes with optional filtering and pagination.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: "Page number for pagination (default: 1)"
        - in: query
          name: limit
          schema:
            type: integer
          description: "Number of items to return per page (default: 10)"
        - in: query
          name: app
          schema:
            type: string
          required: true
          description: Filter wishes by app_id
        - in: query
          name: name
          schema:
            type: string
          description: Filter wishes by name (case-insensitive search)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/GetWishesResponseItem"
                  meta:
                    $ref: "#/components/schemas/PaginationMeta"

    post:
      tags:
        - Wishes   
      summary: Create Wishes
      description: Create a new wish entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FormWishes"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  request:
                    $ref: "#/components/schemas/FormWishes"

components:
  schemas:
    PaginationMeta:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer

    GetWishesResponseItem:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        wishes:
          type: string

    FormWishes:
      type: object
      properties:
        app_id:
          type: integer
        Name:
          type: string
        Wishes:
          type: string
